### PR TITLE
support LJ_GC64

### PR DESCRIPTION
**Pull request by luobing2017**
for LUAJIT_ENABLE_GC64

### CODE REVIEW

**Comment by agentzh** [comment]
@luobing2017 I think you should put `luajit21-gc64` directory under `samples/` instead, like `samples/luajit21-gc64/*.sxx`. These are still samples instead of being direct components of the `stap++` compiler.

**Comment by luobing2017** [comment]
@agentzh yes, other samples work fine and do not need modify

i will put `luajit21-gc64` to `samples/`, so where can i put the new `luajit.sxx`? also under `samples/luajit21-gc64/` or `tapset/luajit21-gc64/`?

**Comment by agentzh** [comment]
@luobing2017 The tapset module should be just renamed to `luajit-gc64.sxx` and it's fine to be under `tapset/`.

**Comment by luobing2017** [comment]
@agentzh done, and i rename new luajit.sxx to luajit_gc64.sxx, not luajit-gc64.sxx, because `@use luajit-gc64` parse error

**Comment by agentzh** [comment]
@luobing2017 Merged. Thanks!

**Pull request closed without merging**
